### ISSUE TITLE
Gene sets from Mosaic and launching into clin.iobio

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#152]
Need functionality in Mosaic to launch a gene set into clin.iobio and need code in clin.iobio to support this

**Comment by mvelinder** [comment]
Decided on adding clin.iobio support for gene and variant set launching. Frameshift will add buttons and UI for launching clin.iobio with gene sets

**Comment by chmille4** [comment]
We added this to our current sprint, so we should have this in master soon.

**Comment by mvelinder** [comment]
Thanks @chmille4 

@anderspitman let's jump on this update when it's on master

**Comment by anderspitman** [comment]
Sounds good. Just let me know @chmille4

**Comment by chmille4** [comment]
Ok new version is released and production wll be updated soon. Issue complete

**Comment by AlistairNWard** [comment]
Just launched clin with a gene set and it seemed to work for me

**Comment by AlistairNWard** [comment]
Clin launches, but no variants are loaded. This could be connected to #140, so maybe this issue is complete, but non-functional till completion of #140.

I created a test gene set in MPPH (called Test) that only has 2 genes. I launch clin, select the Test gene set and it launches. I go to review variants, and the two genes are there, but don't get analyzed. Clicking somewhere else then back on Review Variants doesn't resolve the problem (as in #140). You have to manually click the genes.
