### ISSUE TITLE
Significance in variant is not linked to the menu bar

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#175]
1. Open clin with demo data and go to variants
2. Add a note to a variant
3. The variant is immediately moved to `Reviewed` in the left panel
4. Click on a different variant and the Findings is updated to show 1 variant marked as unknown significance
5. The variant itself is still marked as Not Reviewed. This needs to be updated to Unknown significance

Issue #376 in gene deals with adding a note to a variant and should be consistent with clin - e.g. making the variant reviewed as Unknown Significance

**Comment by adityaekawade** [comment]
@AlistairNWard I think this issue is fixed in gene.iobio and the behaviour is now consistent with Clin. 

1. Add a note to a variant
2. The variant is moved to `Reviewed` in the left panel and is marked as **unknown significance**. 
3. The badge in the navbar shows 1 variant marked as unknown significance and the finding page also shows this variant marked as **unknown significance**.

**Comment by WilliamRichards2017** [comment]
Yeah, this issue was fixed in the https://github.com/iobio/gene.iobio.vue/pull/461 gene.iobio PR

**Comment by AlistairNWard** [comment]
Yep, looks good to me

**Comment by mvelinder** [comment]
Added review complete based on @AlistairNWard 's comment above
