### ISSUE TITLE
Running close message?

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#264]
This happened at the loading status dialogue

![image](https://user-images.githubusercontent.com/22081541/88218661-938f9580-cc1d-11ea-9630-01815c35854f.png)

The language and wording is confusing, I'm not sure what it is trying to convey. That it is running but you can still cancel it? But you can't actually click cancel to cancel it.

It eventually resolved and gave an X 

![image](https://user-images.githubusercontent.com/22081541/88218788-c6398e00-cc1d-11ea-968b-34033d46e98a.png)

**Comment by adityaekawade** [comment]
This needs to be formatted. 
"Running" indicates the status that Phenolyzer is running.  
"Close" allows to cancel this request if the phenolyzer takes a long time. 
The "x" icon indicates that the request is canceled.

**Comment by adityaekawade** [comment]
I had added the "close" text because the phenolyzer service would sometimes take a long time to return a response. And the user could cancel this request by clicking it. 
Now, after moving the phenolyzer to the new backend, the response is considerably faster for new phenotypes. It's not instantaneous but it also does not keep spinning forever. So I have decided to take out the "Running", "close" message from this dialog. 

And it would simply look like this: 
<img width="987" alt="Screen Shot 2020-07-24 at 10 41 51 AM" src="https://user-images.githubusercontent.com/16284713/88420110-37528000-cd9b-11ea-99ec-851d17bd2bfa.png">

If the user still thinks that it is taking a long time, he can still exit the modal and it will run in the background and return a response. He can still see the status in the "terms" panel on the screen. 
<img width="650" alt="Screen Shot 2020-07-24 at 10 42 03 AM" src="https://user-images.githubusercontent.com/16284713/88420456-c8c1f200-cd9b-11ea-92d5-b8c34f915ac5.png">


If the request fails, a red error icon is shown. I have also added a tooltip for this icon. 
<img width="657" alt="Screen Shot 2020-07-24 at 10 40 59 AM" src="https://user-images.githubusercontent.com/16284713/88420349-97e1bd00-cd9b-11ea-89c3-3076d1e1bdea.png">

Test- http://dev.clin.iobio.io/
