### ISSUE TITLE
Add "reads/variants sampled" progress indicator

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#273]
Similar to bam.iobio and vcf.iobio, we could add a progress indicator for the user.

![image](https://user-images.githubusercontent.com/22081541/89181021-1682eb00-d550-11ea-933f-90974d39474d.png)

It would be especially helpful for users who are providing their own data to see progress. I also think it looks really impressive that we're sampling that many things that quickly and giving visualizations of it

**Comment by adityaekawade** [comment]
@mvelinder I like this idea of showing "reads/variants sampled" as a progress indicator for the custom data. Currently, it is sampling a much lesser for the users who are providing their own data. This is to have a faster load time (#213 ). I played around by changing the sampling multiplier value and we can sample between 40-50k variants however, it can take a long time. Also bam.iobio and vcf.iobio works on a single file bam or vcf file. But here we are having multiple samples and hence multiple files. 

I have currently added skeleton loaders to show that the content is loading. I also think it will be really cool to show the visualizations updating in real-time as the data is sampled. 

The screenshot you have attached is for demo data which is using the static values for the data instead of sampling it.

**Comment by adityaekawade** [comment]
@mvelinder I like this idea of showing "reads/variants sampled" as a progress indicator for the custom data. Currently, it is sampling a much lesser for the users who are providing their own data. This is to have a faster load time (#213 ). I played around by changing the sampling multiplier value and we can sample between 40-50k variants however, it can take a long time. Also bam.iobio and vcf.iobio works on a single file bam or vcf file. But here we are having multiple samples and hence multiple files.
I have currently added skeleton loaders to show that the content is loading.

The screenshot you have attached is for demo data which is using the static values for the data instead of sampling it.

**Comment by adityaekawade** [comment]
I refactored most parts of this component for the custom data. The review page now shows the number of reads and variants sampled while the data is being sampled. The user doesn't have to wait and look at the loading screen while all the data is sampled and the visualizations are created. Also, The visualizations update while the data is being sampled. I think it's looking cool as the visualizations update in real-time. 

1. When the page is mounted: 
<img width="1542" alt="Screen Shot 2020-08-12 at 3 06 43 PM" src="https://user-images.githubusercontent.com/16284713/90074506-43ea3a00-dcb0-11ea-90f6-77d29586a38a.png">

2. When the sampling starts: 
<img width="1438" alt="Screen Shot 2020-08-12 at 3 29 03 PM" src="https://user-images.githubusercontent.com/16284713/90074746-b65b1a00-dcb0-11ea-9293-32a851dc0160.png">

3. After receiving data: 
<img width="1593" alt="Screen Shot 2020-08-12 at 3 29 55 PM" src="https://user-images.githubusercontent.com/16284713/90074801-cecb3480-dcb0-11ea-9800-75687c99f5cb.png">

I feel this also addresses issue #213
