### ISSUE TITLE
Only reanalyze the new genes instead of all genes

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#312]
Launch clin with demo data
Add genes from phenotypes or otherwise
Analyze variants and assign a significance
Go back to gene/phenotype entry and manually add a gene
Review variant step reanalysis all genes again

It'd be better to reanalyze only the newly added gene(s). It can get unwieldy quick if they are analyze 50+ genes and every time they add one more they have to reanalyze all of them again.

**Comment by AlistairNWard** [comment]
Absolutely. We should never be redoing work we've already done

**Comment by AlistairNWard** [comment]
@adityaekawade and I looked into this one. It looks like gene.iobio also reanalyzes genes as well. I have some examples of this, but basically if you add a single gene in the top menu of gene.iobio, it only analyzes that new gene. As expected. If, however, you open the gene list option so you can see all selected genes, and add one gene to the end of the list (functionally, exactly the same action as just described just via the list rather than single gene input), gene.iobio will reanalyze all genes. BUT - gene.iobio is caching results, so it skips over the previously defined genes really quickly and all effort goes on the new gene.

Clin.iobio is always passing a gene list to gene, so it's always hitting the scenario where it reanalyzes all genes. It looks like there is a problem with the caching on clin.iobio though, and that is causing a problem. So, there appear to be 2 issues:

1. Fix gene.iobio to check for newly added genes and only analyze those (I'll add an issue to gene.iobio for this)
2. Fix the caching in clin, so even if we do reanalyze genes, the cached genes should be practically instantaneous

This issue should just resolve point 2, caching in clin

**Comment by adityaekawade** [comment]
The cache seems to be working in clin.  I tried the following:
Load demo data > Go directly to review variants > Let the variants load.  The “ANALYZE ALL ELAPSED TIME” in the console is “11.927 seconds” for 8 genes and 9 variants.

Next, I went to step 2 and add RAI1 gene and went back to step 3 > Analyzing glyph was seen but it went a bit quicker this time > The “ANALYZE ALL ELAPSED TIME” in the console is “8.915 seconds” for 9 genes and 10 variants. If it was reanalyzing all genes, it should have taken more time now as there is an extra gene added.


https://user-images.githubusercontent.com/16284713/109331574-da77e600-7811-11eb-9831-9171a79cf6b5.mov

The above video should also show that only new genes take time to be analyzed, and the behavior is similar to gene.iobio.. However. there is a slight freeze when you move from step2 to step 3. This is most likely caused as events are passed from clin to gene.iobio iframe. d3 visualizations are re-rendering and the variants tab switches to the genes tab. I will try to address this in a separate issue.
