### ISSUE TITLE
Genes from select-phenotypes are bypassed in review-variants

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#365]
From Matt - Just using the demo data on stage. Clicking through Phenotypes, not changing anything, going to Variant review, and getting unknown gene message for WARS1. Which is apparently #9 in the list. gene.iobio also doesn't have WARS1 available via the typeahead. I'm not sure why though because HUGO definitely has WARS1 as an accepted gene name/symbol https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:12729

Also fairly weird for the app to recommend a gene (as #9 no less) in step 2 and then throw it out in step 3 because it doesn't recognize it

**Comment by AlistairNWard** [comment]
This isn't a clin issue, rather an issue with the database that gene uses for getting coordinates based on gene names. The gene.iobio database is based on refseq and gencode, so if a gene isn't in there, then gene won't recognise it. We cannot guarantee that because genepanel outputs a gene, that gene.iobio will recognise it, unless we ensure that every gene in any panel submitted to GTR, and any gene in any db associated with Phenolyzer is in our list.

It will also be the case that Mosaic will have a set of genes and this might not be in sync with gene.iobio.

So, this isn't a clin issue, but we should try to have as broad a set of genes as possible and also try to sync Mosaic (currently only has Ensembl genes) with iobio.

**Comment by mvelinder** [comment]
Yes, a much larger issue it seems. I'm happy to help identify and decide on databases that are the most comprehensive and inclusive so we don't run into this

**Comment by AlistairNWard** [comment]
Yeah, I'm pro doing this. We just moved the Mosaic database over to using Ensembl ids, mainly because we want human, mouse, zebrafish etc. and Ensembl seems like a good starting place to get a comprehensive set of accepted genes for all organisms. But Ensembl is not complete, so getting all our tools working from a common, understood combined set of genes would be smart.

I know we want to add in all HGNC genes that don't have Ensembl ids, but if we had a good list of resources, that would be a good place to be in

**Comment by mvelinder** [comment]
See #446 for follow up, closing this
