### ISSUE TITLE
Card styling

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#421]
There is quite a large gap between the top of the card and the title:

![Screen Shot 2021-07-27 at 10 57 12 AM](https://user-images.githubusercontent.com/523111/127177297-e91a3963-d47a-4e53-8ccd-4fd997706fa4.png)

Also, should we just have the titles in black, rather than the blue?

Here is a card from Mosaic. I quite like the style here (we can discuss). We also include a card description in Mosaic which might be useful

![Screen Shot 2021-07-27 at 10 58 48 AM](https://user-images.githubusercontent.com/523111/127177566-707c4b7d-210d-4f4b-aee3-b8f778839317.png)

**Comment by adityaekawade** [comment]
I was trying to get the same padding size from Mosaic, and I found both have the same padding of 16px because of a Vuetify class. But for some reason, the gap looks so big in genepanel. I am reducing the padding so the gap looks small. 


<img width="436" alt="Screen Shot 2021-07-30 at 3 22 24 PM" src="https://user-images.githubusercontent.com/16284713/127717394-28feb966-4d93-4321-9c2e-c72c944f964c.png">


<img width="422" alt="Screen Shot 2021-07-30 at 3 22 47 PM" src="https://user-images.githubusercontent.com/16284713/127717397-cbf951d3-2404-42c4-8e8a-6c98f1e401f0.png">

**Comment by AlistairNWard** [comment]
Weird. I know nothing of the web arts, but it seems like the padding is 16px in both cases, but in Mosaic, the text completely fills the box (e.g. Variant is pushed right up against the top of the text box), but Inputs does not fill the text box in the same way. So in genepanel, there is 16px padding plus some additional padding inside the text box

**Comment by adityaekawade** [comment]
![Screen Shot 2021-08-16 at 12 08 19 PM](https://user-images.githubusercontent.com/16284713/129609937-26bbe88b-549f-4c1a-8944-3eefeb73354c.png)

Reduced the gap between the top and title and also made the title in black. 
Test: https://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
You mentioned that you need to do more modifications. Is that still true? If not, it looks good to me.

**Comment by adityaekawade** [comment]
Oh. Sorry I forgot to comment here. It's fixed.

**Comment by AlistairNWard** [comment]
Thought so. Good to go as far as I'm concerned
